Update snap binary names to snaptel/snapteld
mkleina/snap-plugin-collector-memcache pull request #1
Opened 2016-11-22 15:47 UTC by mkleina

2016-11-28 13:39 UTC, katarzyna-z requested changes

2016-11-28 13:39 UTC, katarzyna-z commented on README.md
> +$ $SNAP_PATH/bin/snapteld -l 1 -t 0 --config config.json
Could you remove $SNAP_PATH from this documentation or correct this line in documentation:
```
$ export SNAP_PATH=<snapDirectoryPath>/build
```
to current localization of snap's binaries?

See this [example](https://github.com/intelsdi-x/snap-plugin-collector-cpu#examples)

If you correct it, please change commit message and tile to of pull request to have full information in them.

2016-11-28 14:52 UTC, mkleina commented on README.md
> +$ $SNAP_PATH/bin/snapteld -l 1 -t 0 --config config.json
Ok, SNAP_PATH updated

2016-11-29 08:35 UTC, katarzyna-z commented on README.md
> +$ $SNAP_PATH/bin/snapteld -l 1 -t 0 --config config.json
Now path should be without ''bin", so it should be
```
 $ $SNAP_PATH/snapteld -l 1 -t 0 --config config.json
```

2016-11-29 10:12 UTC, mkleina commented on README.md
> +$ $SNAP_PATH/bin/snapteld -l 1 -t 0 --config config.json
Ok, binary path changed, now it is $SNAP_PATH instead of $SNAP_PATH/bin

2016-11-29 10:22 UTC, katarzyna-z approved these changes
LGTM

2016-11-29 10:28 UTC, merged